from pathlib import Path

from src.core.contracts import (
    DatabaseRegistryContract,
    DataCatalogContract,
    MetricsContract,
    ProcessedCompanyContract,
    USFactContract,
    USNarrativeContract,
    USTickerContract,
)

# Configuration mapping Contracts to their SQL table names and specific primary keys if any.
# If primary key is empty list, we don't add a PRIMARY KEY clause (useful if we just want raw logs).
CONTRACTS = {
    "metrics": {"model": MetricsContract, "primary_key": []},
    "processed_companies": {"model": ProcessedCompanyContract, "primary_key": ["ticker"]},
    "tickers": {"model": USTickerContract, "primary_key": ["ticker"]},
    "company_facts": {
        "model": USFactContract,
        "primary_key": ["ticker", "accession_number", "label"],
    },
    "narratives": {
        "model": USNarrativeContract,
        "primary_key": ["ticker", "accession_number", "section_name"],
    },
    "databases": {"model": DatabaseRegistryContract, "primary_key": ["db_id"]},
    "data_catalog": {"model": DataCatalogContract, "primary_key": ["partition_key"]},
}

TYPE_MAP = {
    "int": "INTEGER",
    "float": "DOUBLE",
    "str": "VARCHAR",
    "bool": "BOOLEAN",
    "date": "DATE",
    "datetime": "TIMESTAMP",
    "bytes": "BLOB",
}


def map_type(annotation, field_name: str = "") -> str:
    if field_name == "fiscal_year":
        return "SMALLINT"

    ann_str = str(annotation)
    if "int" in ann_str:
        return "INTEGER"
    if "float" in ann_str:
        return "DOUBLE"
    if "bool" in ann_str:
        return "BOOLEAN"
    if "datetime.date" in ann_str and "datetime.datetime" not in ann_str:
        return "DATE"
    if "date" in ann_str and "datetime" not in ann_str:
        return "DATE"
    if "datetime" in ann_str:
        return "TIMESTAMP"
    if "bytes" in ann_str:
        return "BLOB"
    return "VARCHAR"


def generate_ddl() -> dict[str, str]:
    ddls = {}
    for table_name, config in CONTRACTS.items():
        model = config["model"]
        pk = config["primary_key"]

        columns = []
        for field_name, field_info in model.model_fields.items():
            db_type = map_type(field_info.annotation, field_name)
            columns.append(f"    {field_name} {db_type}")

        if pk:
            pk_str = ", ".join(pk)
            columns.append(f"    PRIMARY KEY ({pk_str})")

        columns_str = ",\n".join(columns)
        ddl = f"CREATE TABLE IF NOT EXISTS {table_name} (\n{columns_str}\n);"
        ddls[table_name] = ddl

    return ddls


def generate_markdown() -> str:
    md_lines = [
        "# Database Schema Documentation",
        "",
        "This document is automatically generated from `src/core/contracts.py` (Schema-as-Code).",
        "Do not edit this file manually. Update the Pydantic models in the contracts file instead.",
        "",
        "## Governance Rules",
        "- **SSoT**: `src/core/contracts.py` is the single source of truth.",
        "- **Migrations**: Sequential versioning via `schema_migrations` table.",
        "- **Registry**: `master.duckdb` tracks all distributed shards.",
        "",
    ]

    for table_name, config in CONTRACTS.items():
        model = config["model"]
        pk = config["primary_key"]
        md_lines.append(f"### Table: `{table_name}`")
        if model.__doc__:
            md_lines.append(f"> {model.__doc__.strip()}")
        md_lines.append("")

        md_lines.append(f"**Primary Key**: `{', '.join(pk) if pk else 'None'}`")
        md_lines.append("")
        md_lines.append("| Column | Type | Description |")
        md_lines.append("| --- | --- | --- |")
        for field_name, field_info in model.model_fields.items():
            db_type = map_type(field_info.annotation, field_name)
            desc = field_info.description or ""
            md_lines.append(f"| `{field_name}` | `{db_type}` | {desc} |")
        md_lines.append("")

    return "\n".join(md_lines)


def write_files():
    # Write Python file with DDLs
    src_dir = Path("src/core")
    schema_gen_path = src_dir / "generated_schema.py"

    ddls = generate_ddl()

    with open(schema_gen_path, "w", encoding="utf-8") as f:
        f.write(
            '"""\nAUTO-GENERATED FILE. DO NOT EDIT.\nGenerated from src/core/contracts.py\n"""\n\n'
        )
        f.write("TABLE_SCHEMAS = {\n")
        for table_name, ddl in ddls.items():
            f.write(f'    "{table_name}": {{\n')
            f.write(f'        "v1": """\n{ddl}\n        """\n')
            f.write("    },\n")
        f.write("}\n\n")
        f.write("INDEX_SCHEMAS = [\n")
        f.write('    "CREATE INDEX IF NOT EXISTS idx_us_tickers_cik ON tickers (cik)",\n')
        f.write(
            '    "CREATE INDEX IF NOT EXISTS idx_us_facts_lookup ON company_facts (ticker, fiscal_year, fiscal_period)",\n'
        )
        f.write(
            '    "CREATE INDEX IF NOT EXISTS idx_us_narratives_lookup ON narratives (ticker, form, section_name)",\n'
        )
        f.write("]\n")

    print(f"Generated {schema_gen_path}")

    # Write Markdown Docs
    docs_dir = Path("docs")
    docs_dir.mkdir(exist_ok=True)
    docs_path = docs_dir / "schema.md"

    with open(docs_path, "w", encoding="utf-8") as f:
        f.write(generate_markdown())

    print(f"Generated {docs_path}")


if __name__ == "__main__":
    write_files()
