from pathlib import Path

from src.core.schema import INDEX_SCHEMAS, TABLE_SCHEMAS


def generate_markdown():
    """
    Parses TABLE_SCHEMAS from src/core/schema.py and generates a Markdown report.
    """
    project_root = Path(__file__).parent.parent
    output_path = project_root / "docs" / "SCHEMA.md"

    lines = [
        "# Database Schema Documentation (Auto-generated)",
        "",
        "This document is automatically generated from `src/core/schema.py`. "
        "Do not edit this file manually.",
        "",
        "## Shards Overview",
        "",
        "- **US**: SEC EDGAR Native Data (Long format)",
        "- **JP**: J-Quants Native Data (Wide format)",
        "- **EDINET**: EDINET Statutory Filings (Wide format, AI-mapped)",
        "- **Traceability**: System audit logs and sync sessions",
        "",
    ]

    for shard_key, tables in TABLE_SCHEMAS.items():
        lines.append(f"## Shard: {shard_key.upper()}")
        lines.append("")

        for table_name, versions in tables.items():
            # Get latest version
            v_key = sorted(versions.keys())[-1]
            sql = versions[v_key]

            lines.append(f"### Table: `{table_name}` ({v_key})")
            lines.append("")

            # Simple SQL parsing to extract columns
            start = sql.find("(")
            end = sql.rfind(")")
            col_block = sql[start + 1 : end].strip()

            lines.append("| Column | Type | Notes |")
            lines.append("| :--- | :--- | :--- |")

            for line in col_block.split("\n"):
                col_line = line.strip().strip(",")
                if (
                    not col_line
                    or col_line.startswith("PRIMARY KEY")
                    or col_line.startswith("FOREIGN KEY")
                ):
                    continue

                parts = col_line.split()
                if len(parts) >= 2:
                    col_name = parts[0].replace('"', "").replace("`", "")
                    col_type = parts[1]
                    notes = " ".join(parts[2:]) if len(parts) > 2 else ""
                    lines.append(f"| **{col_name}** | `{col_type}` | {notes} |")

            lines.append("")

        # Indexes
        if INDEX_SCHEMAS.get(shard_key):
            lines.append(f"#### Indexes for {shard_key.upper()}")
            for idx_sql in INDEX_SCHEMAS.get(shard_key, []):
                lines.append(f"- `{idx_sql}`")
            lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Schema documentation generated at {output_path}")


if __name__ == "__main__":
    generate_markdown()
